const ONE_COLUMN_LAYOUT = 'ONE_COLUMN_LAYOUT';
const TWO_COLUMN_LAYOUT = 'TWO_COLUMN_LAYOUT';
const THREE_COLUMN_LAYOUT = 'THREE_COLUMN_LAYOUT';

export { ONE_COLUMN_LAYOUT, TWO_COLUMN_LAYOUT, THREE_COLUMN_LAYOUT };
